### ISSUE TITLE
Source map support in jscover?

### ISSUE THREAD

**Issue by binodpanta** [tntim96/JSCover#224]
Reposting this question https://sourceforge.net/p/jscover/discussion/general/thread/102a5fba/

Sorry if the question is not right on target, but there is a use case we need to fulfill, will try to describe here.

Esp with impending ES6 and Babel adoption (where babel will transpile es6 to es5 code), we are being asked to look into what we can do to show original sources in coverage report, so is there a way to use source maps with jscover? Source maps could be either for babel transpilation or for minification. Either way, goal is to see coverage for original source somehow. 

Also since jscover does store original-src in the report, if source map is also available on disk somewhere, can that somehow be leveraged in jscover?

**Comment by tntim96** [comment]
Currently JSCover doesn't support source maps.

One problem is that JSCover instruments lines, not statements, so it will overstate the coverage for code that was minified when instrumented, but should be OK for code that was only transpiled.

Given the above, would this still be useful for you?

Otherwise I'd have to make a fairly major change to instrument statements instead of lines, which I may do one day.

**Comment by tntim96** [comment]
Rather than instrument the transpiled or minified code and work back to the source via the map, it may be possible for JSCover to map the URI to the file-system, and instrument the original source from the file-system.

**Comment by cobexer** [comment]
ES6 support in JSCover would be awesome!
Is there an ES6 status somewhere? Would be interesting to know which features are supported already.

**Comment by tntim96** [comment]
http://mozilla.github.io/rhino/compat/engines.html

**Comment by tntim96** [comment]
Have you tried instrumenting before transpiling? I've just finished #255 , so this should work better than before. Let me know if you intend to try this out - I'd be happy to support and document the process.

**Comment by karottenreibe** [comment]
@tntim96 I've been experimenting with adding source map support to JSCover and have a basic prototype ATM. If I fleshed that out and prepared a pull request, would you welcome that contribution?

I'd like to know if this is something you'd consider merging before I invest a lot of time making it "nice" ;-)

**Comment by tntim96** [comment]
Sure. That's sounds great. I'd just need enough to see how it operates on a simple sample and how to support it and document it to make the final call on that.

**Comment by karottenreibe** [comment]
Awesome @tntim96 ! I wrote a summary of my changes and the implications I can foresee so far below. Please let me know if there's other info you need from me to make a decision. You can have a look at my current prototype here: https://github.com/tntim96/JSCover/compare/master...karottenreibe:master?w=1

Unfortunately IntelliJ applied some auto-formatting on check-in and messed up the license comments in some files, which make the diff larger than it should be. If you decide to move forward with this I'll revert these changes, of course, and tidy up the diff to make review for you as easy as possible.

Also please note that there are several rough edges yet that I'd clean up before submitting a pull request to you (TODO comments, some things not yet fully implemented, missing tests, etc). If you'd like to move forward, please also let me know if you see any code style issues etc. that you'd like me to address before I submit anything. The earlier I know about them, the easier for me to adhere to your preferred style :-)

# Basic outline of the changes made:

- Introduced a SourceMap type to handle all source map related tasks
  - converting from generated file offsets to original source lines
  - keeping track of which lines in the original source file are "coverable/valid"
- Added a special type of SourceMap for the still supported case of "there is no source map"
  - line instrumentation behaves as before
  - validLines counting behaves as before
- some bug fixes for instrumentation errors I got with my example projects once they were minified
  - no instrumentation statements added between return and returned expression
  - no instrumentation statements added inside for (... in ...) and for (... of ...)
- so far all of this is only implemented for proxy mode, but could be made to work analogously for the other modes
- the code reuses the source map parsing code from Google closure
- tests still run with minor modifications due to method signature changes
- coverage goal is not met ATM (still missing tests for my new code and my fixes in the NodeProcessor)

# Workflow for proxy mode

- When the InstrumentingRequestHandler is asked to instrument a .js file, it tries to fetch the .map file for it
  - the prototype currently just tries to fetch jsfile.js.map when jsfile.js is being instrumented. Must be replaced with a proper lookup via the source map comment
- If no map file can be found: create NoOpSourceMap and pass to instrumenterService
- Else create SourceMapV3 and pass to instrumenterService
  - Google Closure only supports V3 source maps at the moment. If in the future more types need to be supported, there should probably be a factory for this, but ATM only supporting v3 seems fine to me. AFAICS that's the format all popular toolchains output
- InstrumenterService passes the SourceMap on to SourceProcessor, on to ParseTreeInstrumenter, on to NodeProcessor
- When NodeProcessor tries to instrument a Node, it will pass the Node's source location to the SourceMap and output an instrumentation statement for the translated source location
  - In case of NoOpSourceMap no translation happens
  - In case of SourceMapV3 the original source file name + line number are returned
- The NodeProcesser informs the SourceMap of every instrumented original source line
  - The SourceMap uses this to keep track of which lines were already instrumented. NodeProcessor skips instrumenting Nodes that refer to the same original source line as a previously instrumented Node
  - The SourceMap also uses this to compile a list of validLines for every original source file
- After instrumenting, the ParseTreeInstrumenter asks the SourceMap for all original source files and their respective validLines and inserts the jsLineInitialization code before the instrumented source code

# Documentation

I didn't write any yet, but probably it would need documentation on

- when are source maps considered, how are they retrieved
- if needed, how to turn that behaviour off (not sure if there should e.g. be a command line switch?)
- limitations, e.g. the compiler might drop lines completely or mangle them so much that we can't generate separate instrumentation statements for them, which might lead to statements being shown as not covered even though they were

# Open questions

- I'm not sure about the impact on the "report" part of JSCover. Can you foresee any changes that would need to be made there to properly support source maps? I already figured out that the validLines are important to be able to calculate the coverage % values in reporting and hope my changes already sufficiently address this, but don't know if there's more to be considered.
- Other parts of JSCover that are impacted by this change that I haven't considered here?

**Comment by karottenreibe** [comment]
If you'd like to test it out, you can

- clone https://github.com/karottenreibe/react-sample-app
- run `yarn build`
- serve the files in the `build` folder via a web server and start JSCover in proxy mode

The JS files will be instrumented based on the source map.

I did my prototyping tests against a larger app at my company for which I unfortunately can't provide source access. But it worked the same there.

**Comment by tntim96** [comment]
> I did my prototyping tests against a larger app at my company for which I unfortunately can't provide source access. But it worked the same there.

That's a great reason to get the code included.

> some bug fixes for instrumentation errors I got with my example projects once they were minified

I can see a problem with:
```
for (
  const [x, y] of m)
                  console.log(x,y);
```
...but am not sure what the other issues are, or if the above is one of the issues you're seeing. I'd need test cases for each fix, so if you can create PRs for these and I could merge fairly quickly, or if you have basic samples and I can add the fixes with tests in `InstrumenterTest`.

> If you'd like to test it out, you can...

I've given this a quick go. When viewed without the proxy I can see the application runs OK, but with it I am getting `TypeError: _$jscoverage['/static/js/2.2e82e802.chunk.js'] is undefined`. My command line is `JSCover-karottenreibe$ java -jar target/dist/JSCover-all.jar -ws --proxy --port=3128 --report-dir=target/test` - is there something I'm missing?

**Comment by tntim96** [comment]
Hi @karottenreibe,

I've got a bit of time to look at this now.

I've put in an isolated fix for one issue in #279. Do you think you can describe the other bugs with new issues? I could probably add the fix and test cases with a bit more information, but also happy to merge your PRs with test cases.

> If you'd like to test it out, you can

I've given this a second go and still get the same error. Have you got some time to check my steps above?

**Comment by karottenreibe** [comment]
I apologize for not responding @tntim96. Work was very busy the last few weeks. I'll try and have a look this week and get back to you!

**Comment by karottenreibe** [comment]
The other two bugs were:

- trying to insert an instrumenter statement between `return` and the returned expression
- trying to insert an instrumenter statement between `class` and the class name (I think, might have been between `class X extends` and the base class name, but definitely under a `class` node)

**Comment by karottenreibe** [comment]
I just gave it another try on my machine: running your command line arguments from IntelliJ works for me. I'll try running it from the built jar file next. I'm running in Firefox. Are you testing with e.g. Chrome? Could that make a difference?
I'll get back to you when I had the time to try out running from the JAR file :-)

**Comment by tntim96** [comment]
> The other two bugs were...

I tried adding tests in [InstrumenterTest](https://github.com/tntim96/JSCover/blob/master/src/test/java/jscover/instrument/InstrumenterTest.java) to simulate the bugs, but haven't reproduced the issues yet. Do you have a minimal sample?

> running your command line arguments from IntelliJ works for me

Strange. Did you push all your changes? I edited my hosts file to have:
```
127.0.0.1 localhost
127.0.0.1 localhost-proxy
```

I served the files with `serve -s build`, set FireFox's proxy to `localhost:3128`, then went to http://localhost-proxy:5000 in FireFox. Can you think of any other difference?

**Comment by karottenreibe** [comment]
I understand now, I was running my tests with `--no-branch --no-function` but didn't think to mention it above. Sorry about that. Can you please retry with these switches?
I did not yet perform any changes for branch and function coverage.

I think function coverage might not even be possible with source maps because we can't really reason about the number of functions in the original source code with just the source map alone (some might have been optimized away by the compile for example). Maybe you have a good idea.

I'll try and see if I can reproduce the bugs I encountered and narrow down the code to a minimal sample. Might take some time though.

**Comment by karottenreibe** [comment]
I can reproduce the bugs with these `InstrumeterTest` test cases:

```java


    @Test
    public void shouldNotInstrumentReturnOfFunction() {
        String source = "return (\n" +
                "function() {\n" +
                "});";
        String instrumentedSource = sourceProcessor.instrumentSource(source);
        String expectedSource = "_$jscoverage['test.js'].lineData[1]++;\n" +
                "return\n" +
                "function() {\n" +
                "  _$jscoverage['test.js'].functionData[0]++;\n" +
                "};\n";
        assertEquals(expectedSource, instrumentedSource);
    }

    @Test
    public void shouldNotInstrumentInsideForOf() {
        String source = "for (\n" +
                "var x of y) { }";
        String instrumentedSource = sourceProcessor.instrumentSource(source);
        String expectedSource = "_$jscoverage['test.js'].lineData[1]++;\n" +
                "for (" +
                "var x of y) { }";
        assertEquals(expectedSource, instrumentedSource);
    }

    @Test
    public void shouldNotInstrumentInsideForIn() {
        String source = "for (\n" +
                "var x in y) { }";
        String instrumentedSource = sourceProcessor.instrumentSource(source);
        String expectedSource = "_$jscoverage['test.js'].lineData[1]++;\n" +
                "for (" +
                "var x in y) { }";
        assertEquals(expectedSource, instrumentedSource);
    }
```
The JS code is a bit weird but apparently sometimes produced by our minimizer.

**Comment by tntim96** [comment]
Thanks.

`shouldNotInstrumentReturnOfFunction` fixed in #280 
`shouldNotInstrumentInsideForIn` fixed in #281 
`shouldNotInstrumentInsideForOf` I think was already fixed in #279 

I'll try the test again with `--no-branch --no-function`

**Comment by tntim96** [comment]
>  I was running my tests with `--no-branch --no-function`

That seems to have fixed it. The report (see attachment below) is a bit unusual: `logo.svg` is included and the source files don't load when trying to view the source, but least I can't start debugging and taking a look now.

[jscover-sourcemap-report.zip](https://github.com/tntim96/JSCover/files/3706389/jscover-sourcemap-report.zip)

**Comment by karottenreibe** [comment]
thanks for testing it again and your continued patience :-)

Yes, we'll have to think about sensible or maybe configurable filters for the report output as the source map may contain all manner of uninteresting artifacts (ours e.g. also contains compiler-generated artifacts), but I haven't tackled that yet.

Thanks for incorporating those bug fixes :-)

**Comment by karottenreibe** [comment]
@tntim96 did you have time to have a deeper look at my proposed changes? Is it going in the right direction generally and should I continue to improve on it or are you generally opposed to adding source map support to jscover?

**Comment by AmitJoki** [comment]
@karottenreibe do you have the fork with your changes?

I am using Webpack + Babel and I am running the instrumentation on the generated file. It works but is very tedious as the entry point is a concatenation of various files.

I have overcome the minification by disabling the minification in Webpack and using the `devtool: source-map` so as to get the output as close to the original source as possible.

But still, it is a combination of multiple files which makes it hard to effectively utilize JSCover's report. Is there anything I can do? @tntim96
